---
- name: Add LXD repo to our sources
  apt_repository:
    repo: ppa:ubuntu-lxc/lxd-stable
    state: present
  become: yes
  become_method: sudo

- name: Install LXD
  apt: pkg={{ item }} state=present
  with_items:
    - lxd
  become: yes
  become_method: sudo

