---
- name: Add the NodeJS PPA
  shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"
  become: yes
  become_method: sudo

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
    update_cache: yes
  become: yes
  become_method: sudo

- name: Update npm
  shell: npm install npm@latest -g
  become: yes
  become_method: sudo
