---
- name: Ensure that apt uses https
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
  become: yes
  become_method: sudo

- name: Install Various dependencies required by the playbook
  apt: pkg={{ item }} state=present
  with_items:
    - ruby
    - gem
    - python-virtualenv
    - python-apt
    - python3-apt
    - python-pip
    - python-dev
    - build-essential
    - glances
  become: yes
  become_method: sudo
