---
- name: Install vim and various dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - vim
    - vim-gtk
    - python-rope
  become: yes
  become_method: sudo

- name: Install ropevim dependency
  shell: pip install ropevim
  become: yes
  become_method: sudo

- name: Download our vim configuration
  git: repo=https://github.com/andrewebdev/vimconfig.git
       dest=~/.vim
       force={{ force_reset }}

- name: Link the vim rc file
  file: src=~/.vim/.vimrc dest=~/.vimrc state=link

- name: Install vim plugins
  shell: vim +PluginInstall +qall

