---
- name: Ensure that neovim dependencies exists
  apt: pkg={{ item }} state=present
  with_items:
    - xclip
    - python-dev
    - python-pip
    - python-flake8
    - python-jedi
    - python3-dev
    - python3-pip
  become: yes
  become_method: sudo

- name: Add neovim repo
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: yes
  become_method: sudo

- name: Install NeoVim
  apt: pkg={{ item }} state=present
  with_items:
    - neovim
  become: yes
  become_method: sudo

- name: Download my neovim config
  git: repo=https://github.com/andrewebdev/neovim-config.git
       dest=~/.config/nvim
       force={{ vim_force }}
  ignore_errors: true

- name: Ensure that NeoVim config folders exists
  file: path={{ item }} state=directory
  with_items:
    - ~/.config/nvim/autoload/

- name: Install NeoVim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: Install neovim python2 libs
  command: pip2 install neovim

- name: Install neovim python3 libs
  command: pip3 install neovim

