---
- name: Ensure that neovim dependencies exists
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  become: yes
  become_method: sudo

- name: Add neovim repo
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: yes
  become_method: sudo

- name: Install NeoVim
  apt: pkg={{ item }} state=present
  with_items:
    - neovim
  become: yes
  become_method: sudo

# - name: Install NeoVim Plugins

